spring:
  application:
    name: tarifit-auth-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/tarifit_auth}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:tarifit-default-secret-key-for-development-only}
  expiration: ${JWT_EXPIRATION:86400} # 24 hours in seconds

# BCrypt Configuration
security:
  bcrypt:
    rounds: ${BCRYPT_ROUNDS:12}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.tarifit: DEBUG
    org.springframework.security: DEBUG